export const SUBACQUIRERS = [
  { id: 170, name: '2M INSTITUICAO DE PAGAMENTOS' },
  { id: 213, name: '4ON BRASIL' },
  { id: 193, name: 'ABEXPAY' },
  { id: 27, name: 'AKIREDE' },
  { id: 219, name: 'AKIREDE' },
  { id: 189, name: 'AMERICAPAY' },
  { id: 200, name: 'AMI' },
  { id: 217, name: 'AQUISIPAY' },
  { id: 176, name: 'ASSINY NEGOCIOS E PAGAMENTOS DIGITAIS' },
  { id: 168, name: 'ATLANTIC PAY' },
  { id: 233, name: 'BARATAO COMBUSTIVEIS' },
  { id: 186, name: 'BLOKKO' },
  { id: 187, name: 'CAKTO PAY LTDA' },
  { id: 195, name: 'CARTOS MEIOS DE PAGAMENTOS E CONSULTORIA LTDA' },
  { id: 15, name: 'CASA DO CREDITO S/A' },
  { id: 203, name: 'CASA DO CREDITO SA' },
  { id: 22, name: 'CDX EXPRESS' },
  { id: 135, name: 'CEOPAG' },
  { id: 76, name: 'CODEPAY MEIOS DE PAGAMENTO LTDA' },
  { id: 156, name: 'COMPROPAY' },
  { id: 239, name: 'COPASTUR' },
  { id: 205, name: 'CREDITT' },
  { id: 221, name: 'CRONOS INSTITUICAO DE PAGAMENTO LTDA' },
  { id: 149, name: 'DELTAPAG SOLUCOES DE PAGAMENTO' },
  { id: 165, name: 'DOK DESPACHANTE' },
  { id: 77, name: 'EAGLE - GESTAO DE NEGOCIOS EIRELI' },
  { id: 237, name: 'EQUIS INSTITUICAO DE PAGAMENTO LTDA' },
  { id: 1, name: 'EUROPAG' },
  { id: 43, name: 'EUROPAG ( FLEX )' },
  { id: 26, name: 'EZ BANK' },
  { id: 31, name: 'FACIL PAY SUB' },
  { id: 209, name: 'FASTPAY SOLUCAO DE PAGAMENTOS LTDA' },
  { id: 131, name: 'FLYPAY' },
  { id: 191, name: 'FUNDOPAY S.A.' },
  { id: 147, name: 'GREG PAY' },
  { id: 196, name: 'HOLY CASH LTDA' },
  { id: 227, name: 'HYPER CASH PAY LTDA' },
  { id: 8, name: 'HYPERLOCAL' },
  { id: 172, name: 'INGRESSE' },
  { id: 63, name: 'KEYPAY SOLUCOES DE PAGAMENTOS' },
  { id: 143, name: 'KIRVANO' },
  { id: 231, name: 'LASTLINK' },
  { id: 235, name: 'LERA MEIOS DE PAGAMENTO' },
  { id: 198, name: 'LIGASEGURA COBRANCAS LTDA' },
  { id: 128, name: 'MAIS TODOS' },
  { id: 225, name: 'MAUPI' },
  { id: 10, name: 'MULTPAG D1' },
  { id: 23, name: 'MULTPAG D14' },
  { id: 17, name: 'MULTPAG D30' },
  { id: 241, name: 'MUSE BRASIL' },
  { id: 211, name: 'MUTUAL BANK' },
  { id: 66, name: 'ORUSPAY VO' },
  { id: 99, name: 'PAGPRIME' },
  { id: 152, name: 'PARCELAMOS TUDO' },
  { id: 67, name: 'PARCELECART' },
  { id: 136, name: 'PAY PRIME' },
  { id: 178, name: 'PAYUP' },
  { id: 86, name: 'PERFECT PAY' },
  { id: 124, name: 'PHOEBUS TECNOLOGIA' },
  { id: 223, name: 'PIXPAY.AI' },
  { id: 101, name: 'PRONTO PAGUEI' },
  { id: 180, name: 'RP3BANK' },
  { id: 14, name: 'SERVPAY D1' },
  { id: 20, name: 'SERVPAY D30' },
  { id: 108, name: 'SIMPAY' },
  { id: 154, name: 'SKY BANK' },
  { id: 229, name: 'SOLPAG SOLUCAO EM PAGAMENTOS' },
  { id: 207, name: 'TBK BANKS AND TRAINING' },
  { id: 184, name: 'TICTO' },
  { id: 30, name: 'TRADEUP GROUP' },
  { id: 82, name: 'VALOREM MEIOS ELETRONICOS DE PAGAMENTO' },
  { id: 44, name: 'VILEVE PAY' },
  { id: 73, name: 'YUME PAY' },
  { id: 11, name: 'YUPI' },
  { id: 93, name: 'ZEIT BANK' },
  { id: 34, name: 'ZOOMPAY' },
];

export const getSubacquirerById = (id) => {
  const numericId = Number(id);
  if (!Number.isFinite(numericId)) return null;
  return SUBACQUIRERS.find((item) => item.id === numericId) || null;
};
